#ifndef EZTEST_D_EZTEST_D_EZTEST_API_H_
#define EZTEST_D_EZTEST_D_EZTEST_API_H_

#include "eztest-compiler.h"
EZTEST_DISABLE_WTRADITIONAL_
EZTEST_DISABLE_WSYSTEM_HEADERS_

#include "eztest-asserts-impl.h"
#include "eztest-lang.h"
#include "eztest-list.h"
#include "eztest-main.h"
#include "eztest-pre-processor.h"
#include "eztest-test-setup.h"

#define EZTEST_TIMED(group, name, msecs)                                       \
 EZTEST_CREATE_TEST_(EZTEST_NS_ eztest_list_get_head(), group, name, msecs,    \
                     EZTEST_LINE_)
#define EZTEST(group, name) EZTEST_TIMED(group, name, 0)

#define EZTEST_F(group, name) EZTEST_UNIMPLEMENTED_("EZTEST_F")
#define EZTEST_F_TIMED(group, name, msecs)                                     \
 EZTEST_UNIMPLEMENTED_("EZTEST_F_TIMED")

#define EZTEST_P(group, name) EZTEST_UNIMPLEMENTED_("EZTEST_P")
#define EZTEST_P_TIMED(group, name, msecs)                                     \
 EZTEST_UNIMPLEMENTED_("EZTEST_P_TIMED")

#define EZTEST_SCOPED_TRACE(msg) EZTEST_UNIMPLEMENTED_("SCOPED_TRACE")

EZTEST_DISABLE_WCXX98_COMPAT_PEDANTIC_
EZTEST_DISABLE_WVARIADIC_MACROS_

#define EZTEST_ASSERT_THROW(...)     EZTEST_UNIMPLEMENTED_("ASSERT_THROW")
#define EZTEST_ASSERT_ANY_THROW(...) EZTEST_UNIMPLEMENTED_("ASSERT_ANY_THROW")
#define EZTEST_ASSERT_NO_THROW(...)  EZTEST_UNIMPLEMENTED_("ASSERT_NO_THROW")
#define EZTEST_ASSERT_NO_FATAL_FAILURE(...)                                   \
 EZTEST_UNIMPLEMENTED_("ASSERT_NO_FATAL_FAILURE")

#define EZTEST_EXPECT_THROW(...)     EZTEST_UNIMPLEMENTED_("EXPECT_THROW")
#define EZTEST_EXPECT_ANY_THROW(...) EZTEST_UNIMPLEMENTED_("EXPECT_ANY_THROW")
#define EZTEST_EXPECT_NO_THROW(...)  EZTEST_UNIMPLEMENTED_("EXPECT_NO_THROW")
#define EZTEST_EXPECT_NO_FATAL_FAILURE(...)                                   \
 EZTEST_UNIMPLEMENTED_("EXPECT_NO_FATAL_FAILURE")

#define EZTEST_ASSERT_PRED1(...) EZTEST_UNIMPLEMENTED_("EZTEST_ASSERT_PRED1")
#define EZTEST_ASSERT_PRED2(...) EZTEST_UNIMPLEMENTED_("EZTEST_ASSERT_PRED2")
#define EZTEST_ASSERT_PRED3(...) EZTEST_UNIMPLEMENTED_("EZTEST_ASSERT_PRED3")
#define EZTEST_ASSERT_PRED4(...) EZTEST_UNIMPLEMENTED_("EZTEST_ASSERT_PRED4")
#define EZTEST_ASSERT_PRED5(...) EZTEST_UNIMPLEMENTED_("EZTEST_ASSERT_PRED5")

#define EZTEST_EXPECT_PRED1(...) EZTEST_UNIMPLEMENTED_("EZTEST_EXPECT_PRED1")
#define EZTEST_EXPECT_PRED2(...) EZTEST_UNIMPLEMENTED_("EZTEST_EXPECT_PRED2")
#define EZTEST_EXPECT_PRED3(...) EZTEST_UNIMPLEMENTED_("EZTEST_EXPECT_PRED3")
#define EZTEST_EXPECT_PRED4(...) EZTEST_UNIMPLEMENTED_("EZTEST_EXPECT_PRED4")
#define EZTEST_EXPECT_PRED5(...) EZTEST_UNIMPLEMENTED_("EZTEST_EXPECT_PRED5")


EZTEST_REENABLE_WVARIADIC_MACROS_
EZTEST_REENABLE_WCXX98_COMPAT_PEDANTIC_


#define EZTEST_ASSERT_TRUE      EZTEST_ASSERT_TRUE_IMPL_
#define EZTEST_ASSERT_FALSE     EZTEST_ASSERT_FALSE_IMPL_
#define EZTEST_ASSERT_EQ        EZTEST_ASSERT_EQ_IMPL_
#define EZTEST_ASSERT_NE        EZTEST_ASSERT_NE_IMPL_
#define EZTEST_ASSERT_LE        EZTEST_ASSERT_LE_IMPL_
#define EZTEST_ASSERT_LT        EZTEST_ASSERT_LT_IMPL_
#define EZTEST_ASSERT_GE        EZTEST_ASSERT_GE_IMPL_
#define EZTEST_ASSERT_GT        EZTEST_ASSERT_GT_IMPL_
#define EZTEST_ASSERT_STREQ     EZTEST_ASSERT_STREQ_IMPL_
#define EZTEST_ASSERT_STRNE     EZTEST_ASSERT_STRNE_IMPL_
#define EZTEST_ASSERT_STRCASEEQ EZTEST_ASSERT_STRCASEEQ_IMPL_
#define EZTEST_ASSERT_STRCASENE EZTEST_ASSERT_STRCASENE_IMPL_
#define EZTEST_ASSERT_FLOAT_EQ  EZTEST_ASSERT_FLOAT_EQ_IMPL_
#define EZTEST_ASSERT_DOUBLE_EQ EZTEST_ASSERT_DOUBLE_EQ_IMPL_
#define EZTEST_ASSERT_NEAR      EZTEST_ASSERT_NEAR_IMPL_

#define EZTEST_EXPECT_TRUE      EZTEST_EXPECT_TRUE_IMPL_
#define EZTEST_EXPECT_FALSE     EZTEST_EXPECT_FALSE_IMPL_
#define EZTEST_EXPECT_EQ        EZTEST_EXPECT_EQ_IMPL_
#define EZTEST_EXPECT_NE        EZTEST_EXPECT_NE_IMPL_
#define EZTEST_EXPECT_LE        EZTEST_EXPECT_LE_IMPL_
#define EZTEST_EXPECT_LT        EZTEST_EXPECT_LT_IMPL_
#define EZTEST_EXPECT_GE        EZTEST_EXPECT_GE_IMPL_
#define EZTEST_EXPECT_GT        EZTEST_EXPECT_GT_IMPL_
#define EZTEST_EXPECT_STREQ     EZTEST_EXPECT_STREQ_IMPL_
#define EZTEST_EXPECT_STRNE     EZTEST_EXPECT_STRNE_IMPL_
#define EZTEST_EXPECT_STRCASEEQ EZTEST_EXPECT_STRCASEEQ_IMPL_
#define EZTEST_EXPECT_STRCASENE EZTEST_EXPECT_STRCASENE_IMPL_
#define EZTEST_EXPECT_FLOAT_EQ  EZTEST_EXPECT_FLOAT_EQ_IMPL_
#define EZTEST_EXPECT_DOUBLE_EQ EZTEST_EXPECT_DOUBLE_EQ_IMPL_
#define EZTEST_EXPECT_NEAR      EZTEST_EXPECT_NEAR_IMPL_

#if !(EZTEST_STRICT_NAMESPACE)
# define TEST_TIMED              EZTEST_TIMED
# define TEST                    EZTEST
# define TEST_F                  EZTEST_F
# define TEST_F_TIMED            EZTEST_F_TIMED
# define TEST_P                  EZTEST_P
# define TEST_P_TIMED            EZTEST_P_TIMED
# define SCOPED_TRACE            EZTEST_SCOPED_TRACE
# define ASSERT_THROW            EZTEST_ASSERT_THROW
# define ASSERT_ANY_THROW        EZTEST_ASSERT_ANY_THROW
# define ASSERT_NO_THROW         EZTEST_ASSERT_NO_THROW
# define ASSERT_NO_FATAL_FAILURE EZTEST_ASSERT_NO_FATAL_FAILURE
# define EXPECT_THROW            EZTEST_EXPECT_THROW
# define EXPECT_ANY_THROW        EZTEST_EXPECT_ANY_THROW
# define EXPECT_NO_THROW         EZTEST_EXPECT_NO_THROW
# define EXPECT_NO_FATAL_FAILURE EZTEST_EXPECT_NO_FATAL_FAILURE
# define ASSERT_TRUE             EZTEST_ASSERT_TRUE
# define ASSERT_FALSE            EZTEST_ASSERT_FALSE
# define ASSERT_EQ               EZTEST_ASSERT_EQ
# define ASSERT_NE               EZTEST_ASSERT_NE
# define ASSERT_LE               EZTEST_ASSERT_LE
# define ASSERT_LT               EZTEST_ASSERT_LT
# define ASSERT_GE               EZTEST_ASSERT_GE
# define ASSERT_GT               EZTEST_ASSERT_GT
# define ASSERT_STREQ            EZTEST_ASSERT_STREQ
# define ASSERT_STRNE            EZTEST_ASSERT_STRNE
# define ASSERT_STRCASEEQ        EZTEST_ASSERT_STRCASEEQ
# define ASSERT_STRCASENE        EZTEST_ASSERT_STRCASENE
# define ASSERT_FLOAT_EQ         EZTEST_ASSERT_FLOAT_EQ
# define ASSERT_DOUBLE_EQ        EZTEST_ASSERT_DOUBLE_EQ
# define ASSERT_NEAR             EZTEST_ASSERT_NEAR
# define ASSERT_PRED1            EZTEST_ASSERT_PRED1
# define ASSERT_PRED2            EZTEST_ASSERT_PRED2
# define ASSERT_PRED3            EZTEST_ASSERT_PRED3
# define ASSERT_PRED4            EZTEST_ASSERT_PRED4
# define ASSERT_PRED5            EZTEST_ASSERT_PRED5


# define EXPECT_TRUE      EZTEST_EXPECT_TRUE
# define EXPECT_FALSE     EZTEST_EXPECT_FALSE
# define EXPECT_EQ        EZTEST_EXPECT_EQ
# define EXPECT_NE        EZTEST_EXPECT_NE
# define EXPECT_LE        EZTEST_EXPECT_LE
# define EXPECT_LT        EZTEST_EXPECT_LT
# define EXPECT_GE        EZTEST_EXPECT_GE
# define EXPECT_GT        EZTEST_EXPECT_GT
# define EXPECT_STREQ     EZTEST_EXPECT_STREQ
# define EXPECT_STRNE     EZTEST_EXPECT_STRNE
# define EXPECT_STRCASEEQ EZTEST_EXPECT_STRCASEEQ
# define EXPECT_STRCASENE EZTEST_EXPECT_STRCASENE
# define EXPECT_FLOAT_EQ  EZTEST_EXPECT_FLOAT_EQ
# define EXPECT_DOUBLE_EQ EZTEST_EXPECT_DOUBLE_EQ
# define EXPECT_NEAR      EZTEST_EXPECT_NEAR
# define EXPECT_PRED1     EZTEST_EXPECT_PRED1
# define EXPECT_PRED2     EZTEST_EXPECT_PRED2
# define EXPECT_PRED3     EZTEST_EXPECT_PRED3
# define EXPECT_PRED4     EZTEST_EXPECT_PRED4
# define EXPECT_PRED5     EZTEST_EXPECT_PRED5

#endif

EZTEST_REENABLE_WTRADITIONAL_
EZTEST_REENABLE_WSYSTEM_HEADERS_

#endif
